name: Publish Schemas

on:
  push:  # Trigger on every push
    branches:
      - '**'  # Run on all branches
    tags:
      - 'v*'  # Also trigger on version tags

jobs:
  validate:
    name: Validate Schemas and Test YAML Files
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js for JSON validation
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Validate JSON schemas
      - name: Validate JSON Schemas
        run: |
          npm install -g ajv-cli
          cd schemas
          for schema in *.json; do
            echo "Validating $schema"
            ajv compile -s "$schema" || exit 1
          done

      # Step 4: Run jnjrender on YAML files in tests
      - name: Test templates on YAML files
        run: |
          pip install jnjrender
          for file in tests/*.yaml; do
            echo "Processing $file with jnjrender..."
            jnjrender templates/ "$file" || exit 1
          done

  release:
    name: Create Release
    needs: validate  # Run only if the validate job succeeds
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # Run only on tag pushes

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Create a release using the existing tag
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            schemas/*.json
          tag_name: ${{ github.ref_name }}  # Use the existing tag that triggered the workflow
          name: Release ${{ github.ref_name }}
          body: |
            This release contains the latest JSON schemas for the project.
            - Published to GitHub Pages
            - Available as individual release assets
          draft: false
          prerelease: false


