name: Publish Schemas

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  publish:
    name: Publish Schemas
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (optional, if needed for JSON validation)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Validate JSON schemas (optional)
      - name: Validate JSON Schemas
        run: |
          npm install -g ajv-cli
          for schema in schemas/*.json; do
            echo "Validating $schema"
            ajv compile -s "$schema" || exit 1
          done

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "schemas-v${{ github.run_number }}"
          release_name: "Schemas Release v${{ github.run_number }}"
          body: |
            This release contains the latest JSON schemas for the project.
            - Published to GitHub Pages
            - Available as individual release assets
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Schema Files
        run: |
          for schema in schemas/*.json; do
            echo "Uploading $schema"
            gh release upload ${{ steps.create_release.outputs.tag_name }} "$schema" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

