name: Publish Schemas

on:
  push:
    tags:
      - '*'  # Trigger only on tag pushes

jobs:
  publish:
    name: Publish Schemas
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (optional, if needed for JSON validation)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Validate JSON schemas (optional)
      - name: Validate JSON Schemas
        run: |
          npm install -g ajv-cli
          for schema in schemas/*.json; do
            echo "Validating $schema"
            ajv compile -s "$schema" || exit 1
          done

      # Step 4: Publish schemas to the `gh-pages` branch
      - name: Publish Schemas to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: schemas
          publish_branch: gh-pages
          commit_message: "Publish updated schemas [skip ci]"

      # Step 5: Create a release using gh CLI
      - name: Create Release
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "Schemas Release ${{ github.ref_name }}" \
            --notes "This release contains the latest JSON schemas for the project.\n- Published to GitHub Pages\n- Available as individual release assets" \
            --target "${{ github.sha }}" \
            --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Upload each schema file as a release asset
      - name: Upload Schema Files
        run: |
          for schema in schemas/*.json; do
            echo "Uploading $schema"
            gh release upload "${{ github.ref_name }}" "$schema" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

