name: Publish Schemas

on:
  push:
    tags:
      - '*'  # Trigger only on tag pushes

jobs:
  publish:
    name: Publish Schemas
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (optional, if needed for JSON validation)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Validate JSON schemas (optional)
      - name: Validate JSON Schemas
        run: |
          npm install -g ajv-cli
          cd schemas
          for schema in *.json; do
            echo "Validating $schema"
            ajv compile -s "$schema" || exit 1
          done

      # Step 4: Create a release and tag it as 'latest'
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            schemas/*.json
          tag_name: latest  # Add the 'latest' tag
          name: Release ${{ github.ref_name }} (Latest)
          body: |
            This release contains the latest JSON schemas for the project.
            - Published to GitHub Pages
            - Available as individual release assets
          draft: false
          prerelease: false


